# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailagent < Formula
  desc "Local workspace for managing coding agents"
  homepage "https://github.com/kumagaias/tailagent"
  version "0.3.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.16/tailagent_0.3.16_darwin_amd64.tar.gz"
      sha256 "11f623c21b059e88a064db9a75600136f4a4672d12ba6d92139c992a65062f22"

      def install
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.16/tailagent_0.3.16_darwin_arm64.tar.gz"
      sha256 "8f0480a54b4df206a7ec233ae4becf2c1aee866c658c1058f02cc5ec2c27e5c9"

      def install
        bin.install "tailagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.16/tailagent_0.3.16_linux_amd64.tar.gz"
      sha256 "a527c32f98f36604d5ce684a1c51ef2764d6a337be5a61410c8e40273c7447d0"
      def install
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.16/tailagent_0.3.16_linux_arm64.tar.gz"
      sha256 "329afe4208b950eb37f7ccf7e89e9f1ce0eec6eacac0fceeab9789f55c8326f6"
      def install
        bin.install "tailagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tailagent version")
  end
end
