# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailagent < Formula
  desc "Local workspace for managing coding agents"
  homepage "https://github.com/kumagaias/tailagent"
  version "0.3.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.18/tailagent_0.3.18_darwin_amd64.tar.gz"
      sha256 "04b9afa7ac70394582695d8c5a76355b8f70e56f400c5153b85fa1fa78d3956f"

      def install
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.18/tailagent_0.3.18_darwin_arm64.tar.gz"
      sha256 "b7e0d37758cc0ab7678233b8f6b581db508e07043a3bdcf76e14315196abf83c"

      def install
        bin.install "tailagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.18/tailagent_0.3.18_linux_amd64.tar.gz"
      sha256 "9d4f669a156dee52c6447c6fe0a4c5c83a7ffda8d05de075160612a1fcb4d909"
      def install
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.18/tailagent_0.3.18_linux_arm64.tar.gz"
      sha256 "a88f146d43383c2cb940ac1888cd0e079e65807e210c82322a91c72e2bb00b7e"
      def install
        bin.install "tailagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tailagent version")
  end
end
