# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailagent < Formula
  desc "Observability, diagnosis, and repair suggestions for AI coding agents"
  homepage "https://github.com/kumagaias/tailagent"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.1.0/tailagent_0.1.0_darwin_amd64.tar.gz"
      sha256 "f334abdcdf5f2115823c923bac9287bea255f97d96e2b308988edbf340d48d12"

      define_method(:install) do
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.1.0/tailagent_0.1.0_darwin_arm64.tar.gz"
      sha256 "cd433d6c9f6a1a9bb847cb99f41e9672c947e6c05a17d5b0816d4522ad717008"

      define_method(:install) do
        bin.install "tailagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.1.0/tailagent_0.1.0_linux_amd64.tar.gz"
      sha256 "30946740e1fe1e1a6619ff8334966a5e22f62e1024da10823779a37bbb72ad28"
      define_method(:install) do
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.1.0/tailagent_0.1.0_linux_arm64.tar.gz"
      sha256 "3c8a4ca6482cb7726b9bc2dd7be0fb2d21024a9c0d4b246e1a8688d49e85dcb0"
      define_method(:install) do
        bin.install "tailagent"
      end
    end
  end

  test do
    system "#{bin}/tailagent", "version"
  end
end
