# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailagent < Formula
  desc "Local workspace for managing coding agents"
  homepage "https://github.com/kumagaias/tailagent"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.4/tailagent_0.3.4_darwin_amd64.tar.gz"
      sha256 "2543aff615405c5801d85b1e8d86b974565380b3f73d0311e71511484473f016"

      define_method(:install) do
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.4/tailagent_0.3.4_darwin_arm64.tar.gz"
      sha256 "cae35a5be7f399d89389997d543d6977bffd03dfaf8075ed25f0a5b800a93726"

      define_method(:install) do
        bin.install "tailagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.4/tailagent_0.3.4_linux_amd64.tar.gz"
      sha256 "11a04f960988a2472b769edd23fcbc3d0f5e3ad5967078b51ce99283ead1d439"
      define_method(:install) do
        bin.install "tailagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailagent/releases/download/v0.3.4/tailagent_0.3.4_linux_arm64.tar.gz"
      sha256 "cf5eb1391fde6a36187989156b16417fe3d73db9428b61724f455a8b881db4d0"
      define_method(:install) do
        bin.install "tailagent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tailagent version")
  end
end
