# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailfeed < Formula
  desc "A tail-style terminal RSS reader"
  homepage "https://github.com/kumagaias/tailfeed"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.14/tailfeed_darwin_amd64.tar.gz"
      sha256 "8714b0c42cbe1978fc75495d29eb4ac359518bc3e7ff242d988adfdfbaac3447"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.14/tailfeed_darwin_arm64.tar.gz"
      sha256 "69f1e7a5761ff209caa550dca8b10fb0b0c601695863aa640b4584987e91eee5"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.14/tailfeed_linux_amd64.tar.gz"
      sha256 "8f93cd77b73224e42a1fff00fc1e0a34ac1c4bffe0f20ec2899cdcf99df459fd"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.14/tailfeed_linux_arm64.tar.gz"
      sha256 "e3b3a09f4e3b87881ed3077b76635785c828b21ebb9ed39ea36747b883aebcc4"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  def caveats
    <<~EOS
      Get started by adding sample feeds (Hacker News, GitHub Blog, and more):
        tailfeed add sample

      Then open the TUI:
        tailfeed
    EOS
  end

  test do
    system "#{bin}/tailfeed", "--version"
  end
end
