# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailfeed < Formula
  desc "A tail-style RSS reader with browser and terminal interfaces"
  homepage "https://github.com/kumagaias/tailfeed"
  version "0.1.37"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.37/tailfeed_darwin_amd64.tar.gz"
      sha256 "290ff3f85b785aa1f05694762fc6733136924178e061c7418df5d3a7bfa6e067"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.37/tailfeed_darwin_arm64.tar.gz"
      sha256 "f8b1a9ba47c13a5c76b31fae7fe2fc4f9019fee0a5ed01d50223eef0d66454a7"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.37/tailfeed_linux_amd64.tar.gz"
      sha256 "65992de9446df0b7f6e0a9e08a22454a304f28c8c6818e75b2cce2d4b1d4e30e"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.37/tailfeed_linux_arm64.tar.gz"
      sha256 "eb356c6f56e1eabbf7bc3954d24e10623ee5d9d36075c85e06d8ff0bcbba3308"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  def caveats
    <<~EOS
      Get started by adding sample feeds (Hacker News, GitHub Blog, and more):
        tailfeed add sample

      Then open the browser UI:
        tailfeed

      Or open the terminal UI:
        tailfeed -t
    EOS
  end

  test do
    system "#{bin}/tailfeed", "--version"
  end
end
