# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailfeed < Formula
  desc "A tail-style RSS reader with browser and terminal interfaces"
  homepage "https://github.com/kumagaias/tailfeed"
  version "0.1.42"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.42/tailfeed_darwin_amd64.tar.gz"
      sha256 "24fef27190ab8d31ded6c53c82580858c05645733f0474c1e9576422584db1d7"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.42/tailfeed_darwin_arm64.tar.gz"
      sha256 "76c3d43e40a0e51b1ec47f0ef0f692c3275d1eb182259cedc8ab140cd414714e"

      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.42/tailfeed_linux_amd64.tar.gz"
      sha256 "f44f6d2fb134bbb3f314cb2652dd30d5e3fdb9672dabb3926ee586f3195e38f7"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumagaias/tailfeed/releases/download/v0.1.42/tailfeed_linux_arm64.tar.gz"
      sha256 "2d716cfcefa15507569debd3dca381c1cbaf801e2f7051edcea2a6c9b499d66d"
      define_method(:install) do
        bin.install "tailfeed"
      end
    end
  end

  def caveats
    <<~EOS
      Get started by adding sample feeds (Hacker News, GitHub Blog, and more):
        tailfeed add sample

      Then open the browser UI:
        tailfeed

      Or open the terminal UI:
        tailfeed -t
    EOS
  end

  test do
    system "#{bin}/tailfeed", "--version"
  end
end
